name: mt_video_player
description: A custom video player that builds on top of the official video_player package by flutter and adds many functionalities.
version: 1.3.0
homepage: https://github.com/mrmostafaei/mt_video_player
repository: https://github.com/mrmostafaei/mt_video_player

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_video_player:
    path: 'packages/flutter_cached_video_player'
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
